apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gatewa-express
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gatewa-express
  template:
    metadata:
      labels:
        app: api-gatewa-express
    spec:
      containers:
      - name: api-gatewa-express
        image: localhost:5000/api-gatewa-express:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: api-gatewa-express
spec:
  selector:
    app: api-gatewa-express
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30080
  type: NodePort
