apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: localhost:5000/user-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3001
        env:
        - name: DB_PRIMARY_HOSTNAME
          value: "postgres"
        - name: POSTGRES_PORT
          value: "5432"
        - name: DB_PRIMARY_USERNAME
          value: "janny"
        - name: DB_PRIMARY_PASSWORD
          value: "Aj189628@"
        - name: DB_PRIMARY_DATABASE_NAME
          value: "ali-express-auth-service"
        - name: PORT
          value: "3001"
        - name: ENCRYPTION_KEY
          value: "Aj189628@"
        - name: ENCRYPTION_KEY_TOKEN
          value: "Aj189628@"
        - name: JWT_SECRET
          value: "Aj189628@"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: NodePort
