http:
  port: 8000
admin:
  port: 9876
apiEndpoints:
  users:
    paths: '/api/v1/auth-service/*'
serviceEndpoints:
  userService:
    url: 'http://user-service:3001'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - users
    policies:
      - cors:
          - action:
              origin: 
                - 'http://localhost:3000'
                - 'http://localhost:7000'
      - proxy:
          - action:
              serviceEndpoint: userService
              changeOrigin: true
